layout_spectrum: 0.023969586424363573
typography_spectrum: 0.6747091274443867
color:
  lightness: 0.6046271618598574
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  saturation: 0.13467463265320673
  brandStrength: 0.5489638928979599
  rhythmicContrast: 0.6732808825507355
coverPrefs:
  filter: false
name: observatory
analytics:
  twitter: simonturner
github: true
description: innovation can lead to social good
author:
  name: simon turner
  url: marquetteturner.com
  email: simon@marquetteturner.com
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
content_rating:
  adult: false
opengraph: {}
title: observatory
