name: observatory
analytics:
  twitter: simonturner
github: true
description: innovation can lead to social good
author:
  name: simon turner
  url: marquetteturner.com
  email: simon@marquetteturner.com
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
layout_spectrum: 0.2502628023560979
color:
  lightness: 0.6670687611840924
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  saturation: 0.5872420838883718
  brandStrength: 0.3997119601438799
  rhythmicContrast: 0.1018278385932087
content_rating:
  adult: false
typography_spectrum: 0.4971116409144631
opengraph: {}
title: observatory
